name: Check Markdown Links

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run link checker on Markdown files
        # Updated to patched version to fix GHSA-65rg-554r-9j5x vulnerability
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --verbose --no-progress './**/*.md'
