name: Dependency Audit

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found — skipping npm install"
          fi

      - name: Run npm audit
        run: |
          if [ -f package.json ]; then
            npm audit --audit-level=moderate
          else
            echo "No package.json found — skipping audit"
          fi
