name: Lint JavaScript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install ESLint
        run: npm install eslint@9 --no-save

      - name: Create ESLint config
        run: |
          echo 'module.exports = [
            {
              files: ["**/*.js"],
              ignores: ["node_modules/**", "sbom/**"],
              languageOptions: {
                ecmaVersion: 2021,
                sourceType: "module"
              },
              rules: {
                "no-unused-vars": "warn",
                "no-console": "off",
                "semi": ["error", "always"],
                "quotes": ["error", "double"]
              }
            }
          ];' > eslint.config.cjs

      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          npx eslint . --config eslint.config.cjs
