name: Lint Markdown

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: "**/*.md"
