name: Lint JavaScript

on:
  push:
    paths:
      - "**/*.js"
  pull_request:
    paths:
      - "**/*.js"

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install ESLint
        run: |
          npm install eslint --no-save

      - name: Create ESLint config (v9+)
        run: |
          echo 'export default [
            {
              files: ["**/*.js"],
              ignores: ["sbom/**", "node_modules/**"],
              languageOptions: {
                ecmaVersion: 2021,
                sourceType: "module"
              },
              rules: {
                "no-unused-vars": "warn",
                "no-console": "off",
                "semi": ["error", "always"],
                "quotes": ["error", "double"]
              }
            }
          ];' > eslint.config.js

      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          npx eslint .
