name: Generate and Commit SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install Syft (SBOM Generator)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: |
          mkdir -p sbom
          syft dir:. -o cyclonedx-json > sbom/sbom.json

      - name: Commit and Push SBOM
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add sbom/sbom.json
          if git diff --cached --quiet; then
            echo "No SBOM changes to commit."
          else
            git commit -m "chore: update SBOM [auto]"
            git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:main
